// This file is generated by scripts/import-csv.ts. Do not edit directly.

import { personalBests } from "./personalBests";
import { resultRecords } from "./results";

export type Athlete = {
  id: string;
  slug: string;
  name: string;
  year: string;
  universityId: string;
  hometown: string;
  specialty: string;
  profile: string;
  pb: { distance: string; time: string; date: string }[];
  nextRace: string;
  recentResults: { event: string; date: string; distance: string; time: string; rank: string }[];
  progress: { label: string; value: number; time: string }[];
  ekiden: { race: string; section: string; result: string }[];
};

export type AthleteRecord = {
  id: string;
  slug: string;
  name: string;
  year: string;
  universityId: string;
  hometown: string;
  specialty: string;
  profile: string;
  nextRace: string;
  progress: Athlete["progress"];
  ekiden: Athlete["ekiden"];
};

const raceNameById: Record<string, string> = {
  "mens-10000m-3": "関東学生10000m記録挑戦会 男子10000m 3組",
  "mens-1500m-final": "関東学生1500m記録会 男子1500m 決勝",
  "half-final": "箱根駅伝予選会プレ記録会 ハーフマラソン 決勝"
};

export const athleteRecords: AthleteRecord[] = [
  {
    "id": "saeki",
    "slug": "saeki",
    "name": "佐伯 蒼",
    "year": "3年",
    "universityId": "aoba",
    "hometown": "",
    "specialty": "10000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "男子5000m A組",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "morino",
    "slug": "morino",
    "name": "森野 健太",
    "year": "4年",
    "universityId": "josai",
    "hometown": "",
    "specialty": "ハーフ",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "箱根駅伝予選会プレ記録会",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "yoshioka",
    "slug": "yoshioka",
    "name": "吉岡 遼",
    "year": "2年",
    "universityId": "surugadai",
    "hometown": "",
    "specialty": "10000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "男子10000m 3組",
    "progress": [],
    "ekiden": []
  }
];

export const athletes: Athlete[] = athleteRecords.map((athlete) => ({
  ...athlete,
  pb: personalBests
    .filter((record) => record.athlete_id === athlete.id)
    .map((record) => ({ distance: record.distance, time: record.time, date: record.date })),
  recentResults: resultRecords
    .filter((result) => result.athlete_id === athlete.id)
    .sort((a, b) => b.date.localeCompare(a.date))
    .map((result) => ({
      event: raceNameById[result.race_id] ?? result.race_id,
      date: result.date,
      distance: result.distance,
      time: result.time,
      rank: result.rank
    }))
}));

export const athleteAliases: Record<string, string> = Object.fromEntries(athleteRecords.map((athlete) => [athlete.id, athlete.name]));

export function getAthleteById(id: string) {
  return athletes.find((athlete) => athlete.id === id);
}
