// This file is generated by scripts/import-csv.ts. Do not edit directly.

import { personalBests } from "./personalBests";
import { resultRecords } from "./results";

export type Athlete = {
  id: string;
  slug: string;
  name: string;
  year: string;
  universityId: string;
  hometown: string;
  specialty: string;
  profile: string;
  pb: { distance: string; time: string; date: string }[];
  nextRace: string;
  recentResults: { event: string; date: string; distance: string; time: string; rank: string }[];
  progress: { label: string; value: number; time: string }[];
  ekiden: { race: string; section: string; result: string }[];
};

export type AthleteRecord = {
  id: string;
  slug: string;
  name: string;
  year: string;
  universityId: string;
  hometown: string;
  specialty: string;
  profile: string;
  nextRace: string;
  progress: Athlete["progress"];
  ekiden: Athlete["ekiden"];
};

const raceNameById: Record<string, string> = {
  "kanto-intercollege-mens-5000m": "関東インカレ 男子5000m 決勝"
};

export const athleteRecords: AthleteRecord[] = [
  {
    "id": "okada-kaisei",
    "slug": "okada-kaisei",
    "name": "岡田 開成",
    "year": "3年",
    "universityId": "chuo",
    "hometown": "大阪",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "suzuki-rui",
    "slug": "suzuki-rui",
    "name": "鈴木 琉胤",
    "year": "2年",
    "universityId": "waseda",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "stephen-lemayan",
    "slug": "stephen-lemayan",
    "name": "ｽﾃｨｰﾌﾞﾝ ﾚﾏｲﾔﾝ",
    "year": "4年",
    "universityId": "surugadai",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "brian-kipiego",
    "slug": "brian-kipiego",
    "name": "ﾌﾞﾗｲｱﾝ ｷﾋﾟｴｺﾞ",
    "year": "4年",
    "universityId": "yamanashi-gakuin",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "kudo-shinsaku",
    "slug": "kudo-shinsaku",
    "name": "工藤 慎作",
    "year": "4年",
    "universityId": "waseda",
    "hometown": "千葉",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "ikema-riito",
    "slug": "ikema-riito",
    "name": "池間 凛斗",
    "year": "3年",
    "universityId": "juntendo",
    "hometown": "沖縄",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "sato-daisuke",
    "slug": "sato-daisuke",
    "name": "佐藤 大介",
    "year": "3年",
    "universityId": "chuo",
    "hometown": "埼玉",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "shibata-yu",
    "slug": "shibata-yu",
    "name": "柴田 侑",
    "year": "4年",
    "universityId": "josai",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "yoshikura-nayabu-naoki",
    "slug": "yoshikura-nayabu-naoki",
    "name": "吉倉 ﾅﾔﾌﾞ直希",
    "year": "3年",
    "universityId": "waseda",
    "hometown": "東京",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "kawasaki-so",
    "slug": "kawasaki-so",
    "name": "川﨑 颯",
    "year": "4年",
    "universityId": "tsukuba",
    "hometown": "大阪",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "yamamoto-haruka",
    "slug": "yamamoto-haruka",
    "name": "山本 悠",
    "year": "3年",
    "universityId": "juntendo",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "kibuni-evans",
    "slug": "kibuni-evans",
    "name": "ｷﾌﾞﾆ ｴｳﾞｧﾝｽ",
    "year": "1年",
    "universityId": "kokushikan",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "noda-akito",
    "slug": "noda-akito",
    "name": "野田 晶斗",
    "year": "4年",
    "universityId": "hosei",
    "hometown": "京都",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "ohama-takuma",
    "slug": "ohama-takuma",
    "name": "大濱 逞真",
    "year": "3年",
    "universityId": "daito-bunka",
    "hometown": "宮城",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "omi-ryo",
    "slug": "omi-ryo",
    "name": "近江 亮",
    "year": "1年",
    "universityId": "daito-bunka",
    "hometown": "宮城",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "kobayashi-ryuki",
    "slug": "kobayashi-ryuki",
    "name": "小林 竜輝",
    "year": "3年",
    "universityId": "josai",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "urabe-towa",
    "slug": "urabe-towa",
    "name": "占部 大和",
    "year": "4年",
    "universityId": "yamanashi-gakuin",
    "hometown": "福岡",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "oshita-tomoya",
    "slug": "oshita-tomoya",
    "name": "大下 智矢",
    "year": "2年",
    "universityId": "juntendo",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "matsuyama-yuta",
    "slug": "matsuyama-yuta",
    "name": "松山 優太",
    "year": "2年",
    "universityId": "tokai",
    "hometown": "三重",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "hamaguchi-yamato",
    "slug": "hamaguchi-yamato",
    "name": "濵口 大和",
    "year": "2年",
    "universityId": "chuo",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "wakabayashi-tsukasa",
    "slug": "wakabayashi-tsukasa",
    "name": "若林 司",
    "year": "1年",
    "universityId": "daito-bunka",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "kobayashi-haru",
    "slug": "kobayashi-haru",
    "name": "小林 晴琉",
    "year": "2年",
    "universityId": "tsukuba",
    "hometown": "愛知",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "murao-kyosuke",
    "slug": "murao-kyosuke",
    "name": "村尾 恭輔",
    "year": "2年",
    "universityId": "josai",
    "hometown": "鳥取",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "sato-yamato",
    "slug": "sato-yamato",
    "name": "佐藤 大和",
    "year": "3年",
    "universityId": "nippon-sport-science",
    "hometown": "新潟",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "takahashi-fuga",
    "slug": "takahashi-fuga",
    "name": "高橋 楓河",
    "year": "3年",
    "universityId": "yamanashi-gakuin",
    "hometown": "秋田",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "ishikawa-yuto",
    "slug": "ishikawa-yuto",
    "name": "石川 悠斗",
    "year": "3年",
    "universityId": "nihon",
    "hometown": "栃木",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "narusawa-shoei",
    "slug": "narusawa-shoei",
    "name": "成沢 翔英",
    "year": "3年",
    "universityId": "keio",
    "hometown": "長野",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "handa-kevin",
    "slug": "handa-kevin",
    "name": "飯田ケビン",
    "year": "2年",
    "universityId": "toyo",
    "hometown": "茨城",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "sano-rinta",
    "slug": "sano-rinta",
    "name": "佐野 鈴太",
    "year": "3年",
    "universityId": "tokai",
    "hometown": "新潟",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "kojima-mitsuki",
    "slug": "kojima-mitsuki",
    "name": "小島 光稀",
    "year": "3年",
    "universityId": "surugadai",
    "hometown": "埼玉",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "higaki-aoi",
    "slug": "higaki-aoi",
    "name": "檜垣 蒼",
    "year": "3年",
    "universityId": "tokai",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "goto-ibuki",
    "slug": "goto-ibuki",
    "name": "後藤 玄樹",
    "year": "2年",
    "universityId": "nihon",
    "hometown": "宮崎",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "shudo-kaito",
    "slug": "shudo-kaito",
    "name": "首藤 海翔",
    "year": "1年",
    "universityId": "nihon",
    "hometown": "岡山",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "hayashi-yua",
    "slug": "hayashi-yua",
    "name": "林 柚杏",
    "year": "1年",
    "universityId": "toyo",
    "hometown": "",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  },
  {
    "id": "matsui-kaito",
    "slug": "matsui-kaito",
    "name": "松井 海斗",
    "year": "3年",
    "universityId": "toyo",
    "hometown": "埼玉",
    "specialty": "5000m",
    "profile": "PBと最近の結果を掲載しています。",
    "nextRace": "",
    "progress": [],
    "ekiden": []
  }
];

export const athletes: Athlete[] = athleteRecords.map((athlete) => ({
  ...athlete,
  pb: personalBests
    .filter((record) => record.athlete_id === athlete.id)
    .map((record) => ({ distance: record.distance, time: record.time, date: record.date })),
  recentResults: resultRecords
    .filter((result) => result.athlete_id === athlete.id)
    .sort((a, b) => b.date.localeCompare(a.date))
    .map((result) => ({
      event: raceNameById[result.race_id] ?? result.race_id,
      date: result.date,
      distance: result.distance,
      time: result.time,
      rank: result.rank
    }))
}));

export const athleteAliases: Record<string, string> = Object.fromEntries(athleteRecords.map((athlete) => [athlete.id, athlete.name]));

export function getAthleteById(id: string) {
  return athletes.find((athlete) => athlete.id === id);
}
