// This file is generated by scripts/import-csv.ts. Do not edit directly.

export type EntryStatus = "entered" | "listed" | "started" | "dns" | "unconfirmed";

export type Entry = {
  entry_id: string;
  meet_id: string;
  race_id: string;
  athlete_id: string;
  university_id: string;
  bib_no: number | null;
  status: EntryStatus;
};

export const entries: Entry[] = [
  {
    "entry_id": "entry-kanto-10000m-saeki",
    "meet_id": "kanto-10000m",
    "race_id": "mens-10000m-3",
    "athlete_id": "saeki",
    "university_id": "aoba",
    "bib_no": 1,
    "status": "entered"
  },
  {
    "entry_id": "entry-kanto-10000m-yoshioka",
    "meet_id": "kanto-10000m",
    "race_id": "mens-10000m-3",
    "athlete_id": "yoshioka",
    "university_id": "surugadai",
    "bib_no": 2,
    "status": "entered"
  },
  {
    "entry_id": "entry-kanto-1500m-saeki",
    "meet_id": "kanto-1500m",
    "race_id": "mens-1500m-final",
    "athlete_id": "saeki",
    "university_id": "aoba",
    "bib_no": 1,
    "status": "entered"
  },
  {
    "entry_id": "entry-half-morino",
    "meet_id": "hakone-qualifier-trial",
    "race_id": "half-final",
    "athlete_id": "morino",
    "university_id": "josai",
    "bib_no": 1,
    "status": "entered"
  }
];

export function getEntriesByRaceId(raceId: string) {
  return entries.filter((entry) => entry.race_id === raceId);
}

export function getEntriesByMeetId(meetId: string) {
  return entries.filter((entry) => entry.meet_id === meetId);
}

export function getEntriesByAthleteId(athleteId: string) {
  return entries.filter((entry) => entry.athlete_id === athleteId);
}

export function getEntriesByUniversityId(universityId: string) {
  return entries.filter((entry) => entry.university_id === universityId);
}
