// This file is generated by scripts/import-csv.ts. Do not edit directly.

export type MeetStatus = "scheduled" | "coming_soon" | "startlist_published" | "result_waiting" | "live" | "result_published";

export type MeetCategory = "track" | "road" | "ekiden";

export type Meet = {
  meet_id: string;
  slug: string;
  meet_name: string;
  date: string;
  venue: string;
  category: MeetCategory;
  status: MeetStatus;
  race_count: number | null;
  published_startlist_count: number;
  published_result_count: number;
  note: string;
};

export const meets: Meet[] = [
  {
    "meet_id": "hakone-ekiden",
    "slug": "hakone-ekiden",
    "meet_name": "箱根駅伝",
    "date": "2026-01-02",
    "venue": "東京〜箱根",
    "category": "ekiden",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "japan-student-half",
    "slug": "japan-student-half",
    "meet_name": "日本学生ハーフ",
    "date": "2026-03-01",
    "venue": "会場未定",
    "category": "road",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "kanaguri-memorial",
    "slug": "kanaguri-memorial",
    "meet_name": "金栗記念",
    "date": "2026-04-01",
    "venue": "会場未定",
    "category": "track",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "japan-student-individual",
    "slug": "japan-student-individual",
    "meet_name": "日本学生個人選手権",
    "date": "2026-04-15",
    "venue": "会場未定",
    "category": "track",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "kanto-intercollege",
    "slug": "kanto-intercollege",
    "meet_name": "関東インカレ",
    "date": "2026-05-24",
    "venue": "会場未定",
    "category": "track",
    "status": "result_published",
    "race_count": 1,
    "published_startlist_count": 1,
    "published_result_count": 1,
    "note": "男子5000m決勝の結果を掲載"
  },
  {
    "meet_id": "golden-games-nobeoka",
    "slug": "golden-games-nobeoka",
    "meet_name": "ゴールデンゲームズ in のべおか",
    "date": "2026-05-10",
    "venue": "会場未定",
    "category": "track",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "all-japan-kanto-qualifier",
    "slug": "all-japan-kanto-qualifier",
    "meet_name": "全日本大学駅伝関東選考会",
    "date": "2026-06-01",
    "venue": "会場未定",
    "category": "track",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "hokuren-dc",
    "slug": "hokuren-dc",
    "meet_name": "ホクレンDC",
    "date": "2026-07-01",
    "venue": "会場未定",
    "category": "track",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "複数大会として分ける場合は開催地ごとにmeet_idを分ける"
  },
  {
    "meet_id": "japan-intercollege",
    "slug": "japan-intercollege",
    "meet_name": "日本インカレ",
    "date": "2026-09-01",
    "venue": "会場未定",
    "category": "track",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "izumo-ekiden",
    "slug": "izumo-ekiden",
    "meet_name": "出雲駅伝",
    "date": "2026-10-01",
    "venue": "出雲",
    "category": "ekiden",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "hakone-qualifier",
    "slug": "hakone-qualifier",
    "meet_name": "箱根予選会",
    "date": "2026-10-15",
    "venue": "会場未定",
    "category": "road",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "all-japan-univ-ekiden",
    "slug": "all-japan-univ-ekiden",
    "meet_name": "全日本大学駅伝",
    "date": "2026-11-01",
    "venue": "熱田〜伊勢",
    "category": "ekiden",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "ageo-city-half",
    "slug": "ageo-city-half",
    "meet_name": "上尾シティハーフ",
    "date": "2026-11-15",
    "venue": "上尾",
    "category": "road",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "hachioji-long-distance",
    "slug": "hachioji-long-distance",
    "meet_name": "八王子ロングディスタンス",
    "date": "2026-11-22",
    "venue": "会場未定",
    "category": "track",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "日程・会場は正式情報確認後に更新"
  },
  {
    "meet_id": "nittaidai-long-distance",
    "slug": "nittaidai-long-distance",
    "meet_name": "日体大長距離競技会",
    "date": "2026-12-01",
    "venue": "会場未定",
    "category": "track",
    "status": "scheduled",
    "race_count": null,
    "published_startlist_count": 0,
    "published_result_count": 0,
    "note": "通年開催のため開催回ごとに分ける運用を推奨"
  }
];

export const meetStatusLabels: Record<MeetStatus, string> = {
  scheduled: "予定",
  coming_soon: "まもなく",
  startlist_published: "スタートリスト公開",
  result_waiting: "結果待ち",
  live: "実施中",
  result_published: "結果公開"
};

export const meetCategoryLabels: Record<MeetCategory, string> = {
  track: "トラック",
  road: "ロード",
  ekiden: "駅伝"
};
