// This file is generated by scripts/import-csv.ts. Do not edit directly.

export type MeetStatus = "scheduled" | "coming_soon" | "startlist_published" | "result_waiting" | "live" | "result_published";

export type MeetCategory = "track" | "road" | "ekiden";

export type Meet = {
  meet_id: string;
  slug: string;
  meet_name: string;
  date: string;
  venue: string;
  category: MeetCategory;
  status: MeetStatus;
  race_count: number | null;
  published_startlist_count: number;
  published_result_count: number;
  note: string;
};

export const meets: Meet[] = [
  {
    "meet_id": "kanto-10000m",
    "slug": "kanto-10000m",
    "meet_name": "関東学生10000m記録挑戦会",
    "date": "2026-05-24",
    "venue": "町田GIONスタジアム",
    "category": "track",
    "status": "result_published",
    "race_count": 1,
    "published_startlist_count": 1,
    "published_result_count": 1,
    "note": "結果公開中"
  },
  {
    "meet_id": "kanto-1500m",
    "slug": "kanto-1500m",
    "meet_name": "関東学生1500m記録会",
    "date": "2026-06-02",
    "venue": "駒沢オリンピック公園陸上競技場",
    "category": "track",
    "status": "result_published",
    "race_count": 1,
    "published_startlist_count": 1,
    "published_result_count": 1,
    "note": "結果公開中"
  },
  {
    "meet_id": "hakone-qualifier-trial",
    "slug": "hakone-qualifier-trial",
    "meet_name": "箱根駅伝予選会プレ記録会",
    "date": "2026-05-18",
    "venue": "相模原ギオンスタジアム",
    "category": "road",
    "status": "result_published",
    "race_count": 1,
    "published_startlist_count": 1,
    "published_result_count": 1,
    "note": "結果公開中"
  }
];

export const meetStatusLabels: Record<MeetStatus, string> = {
  scheduled: "予定",
  coming_soon: "まもなく",
  startlist_published: "スタートリスト公開",
  result_waiting: "結果待ち",
  live: "実施中",
  result_published: "結果公開"
};

export const meetCategoryLabels: Record<MeetCategory, string> = {
  track: "トラック",
  road: "ロード",
  ekiden: "駅伝"
};
