// This file is generated by scripts/import-csv.ts. Do not edit directly.

export type MeetStatus = "scheduled" | "coming_soon" | "startlist_published" | "result_waiting" | "live" | "result_published";

export type MeetCategory = "track" | "road" | "ekiden";

export type Meet = {
  meet_id: string;
  slug: string;
  meet_name: string;
  date: string;
  venue: string;
  category: MeetCategory;
  status: MeetStatus;
  race_count: number | null;
  published_startlist_count: number;
  published_result_count: number;
  note: string;
};

export const meets: Meet[] = [
  {
    "meet_id": "kanto-intercollege",
    "slug": "kanto-intercollege",
    "meet_name": "関東インカレ",
    "date": "2026-05-24",
    "venue": "会場未定",
    "category": "track",
    "status": "result_published",
    "race_count": 4,
    "published_startlist_count": 4,
    "published_result_count": 4,
    "note": "男子5000m決勝の結果を掲載"
  },
  {
    "meet_id": "japan-student-individual",
    "slug": "japan-student-individual",
    "meet_name": "2026日本学生陸上競技個人選手権大会",
    "date": "2026-04-24",
    "venue": "レモンガススタジアム平塚",
    "category": "track",
    "status": "result_published",
    "race_count": 2,
    "published_startlist_count": 2,
    "published_result_count": 2,
    "note": "天皇賜盃第95回日本インカレ男子10000mを併催"
  },
  {
    "meet_id": "kanto-intercollege-half",
    "slug": "kanto-intercollege-half",
    "meet_name": "第105回関東学生陸上競技対校選手権大会 ハーフマラソン",
    "date": "2026-04-05",
    "venue": "静岡県焼津市",
    "category": "road",
    "status": "result_published",
    "race_count": 2,
    "published_startlist_count": 2,
    "published_result_count": 2,
    "note": "男子1部ハーフマラソン決勝の結果を掲載"
  },
  {
    "meet_id": "all-japan-kanto-qualifier",
    "slug": "all-japan-kanto-qualifier",
    "meet_name": "秩父宮賜杯第58回全日本大学駅伝対校選手権大会 関東選考会",
    "date": "2026-05-04",
    "venue": "レモンガススタジアム平塚",
    "category": "track",
    "status": "result_published",
    "race_count": 1,
    "published_startlist_count": 1,
    "published_result_count": 1,
    "note": "男子10000mタイムレース総合結果を掲載"
  },
  {
    "meet_id": "golden-games-nobeoka",
    "slug": "golden-games-nobeoka",
    "meet_name": "第37回ゴールデンゲームズ in のべおか",
    "date": "2026-05-04",
    "venue": "西階陸上競技場",
    "category": "track",
    "status": "result_published",
    "race_count": 1,
    "published_startlist_count": 1,
    "published_result_count": 1,
    "note": "男子5000mタイムレース総合の大学所属選手を掲載"
  },
  {
    "meet_id": "kanaguri-memorial",
    "slug": "kanaguri-memorial",
    "meet_name": "第34回 金栗記念選抜陸上中長距離熊本大会",
    "date": "2026-04-11",
    "venue": "えがお健康スタジアム",
    "category": "track",
    "status": "result_published",
    "race_count": 2,
    "published_startlist_count": 2,
    "published_result_count": 2,
    "note": "男子グランプリ5000mの大学所属選手を掲載"
  }
];

export const meetStatusLabels: Record<MeetStatus, string> = {
  scheduled: "予定",
  coming_soon: "まもなく",
  startlist_published: "スタートリスト公開",
  result_waiting: "結果待ち",
  live: "実施中",
  result_published: "結果公開"
};

export const meetCategoryLabels: Record<MeetCategory, string> = {
  track: "トラック",
  road: "ロード",
  ekiden: "駅伝"
};
