// This file is generated by scripts/import-csv.ts. Do not edit directly.

export type PbDistance = "1500m" | "5000m" | "10000m" | "ハーフ";

export type PersonalBest = {
  pb_id: string;
  athlete_id: string;
  university_id: string;
  distance: PbDistance;
  time: string;
  date: string;
  source_type?: "result" | "manual";
  source_result_id?: string;
};

export const personalBests: PersonalBest[] = [
  {
    "pb_id": "pb-saeki-10000m",
    "athlete_id": "saeki",
    "university_id": "aoba",
    "distance": "10000m",
    "time": "28:28.90",
    "date": "2026-05-24",
    "source_type": "result",
    "source_result_id": "kanto-10000m-mens-10000m-3-saeki"
  },
  {
    "pb_id": "pb-saeki-1500m",
    "athlete_id": "saeki",
    "university_id": "aoba",
    "distance": "1500m",
    "time": "3:48.20",
    "date": "2026-06-02",
    "source_type": "result",
    "source_result_id": "kanto-1500m-mens-1500m-final-saeki"
  },
  {
    "pb_id": "pb-morino-half",
    "athlete_id": "morino",
    "university_id": "josai",
    "distance": "ハーフ",
    "time": "1:02:48",
    "date": "2026-05-18",
    "source_type": "result",
    "source_result_id": "hakone-qualifier-trial-half-final-morino"
  }
];

export function getPersonalBestsByAthleteId(athleteId: string) {
  return personalBests.filter((record) => record.athlete_id === athleteId);
}
