// This file is generated by scripts/import-csv.ts. Do not edit directly.

export type PbDistance = "1500m" | "5000m" | "10000m" | "ハーフ";

export type PersonalBest = {
  pb_id: string;
  athlete_id: string;
  university_id: string;
  distance: PbDistance;
  time: string;
  date: string;
  source_type?: "result" | "manual";
  source_result_id?: string;
};

export const personalBests: PersonalBest[] = [
  {
    "pb_id": "pb-kudo-shinsaku-5000m",
    "athlete_id": "kudo-shinsaku",
    "university_id": "waseda",
    "distance": "5000m",
    "time": "13:38.67",
    "date": "2026-05-24",
    "source_type": "result",
    "source_result_id": "kanto-intercollege-mens-5000m-kudo-shinsaku"
  },
  {
    "pb_id": "pb-omi-ryo-5000m",
    "athlete_id": "omi-ryo",
    "university_id": "daito-bunka",
    "distance": "5000m",
    "time": "13:54.99",
    "date": "2026-05-24",
    "source_type": "result",
    "source_result_id": "kanto-intercollege-mens-5000m-omi-ryo"
  },
  {
    "pb_id": "pb-kobayashi-haru-5000m",
    "athlete_id": "kobayashi-haru",
    "university_id": "tsukuba",
    "distance": "5000m",
    "time": "14:06.50",
    "date": "2026-05-24",
    "source_type": "result",
    "source_result_id": "kanto-intercollege-mens-5000m-kobayashi-haru"
  }
];

export function getPersonalBestsByAthleteId(athleteId: string) {
  return personalBests.filter((record) => record.athlete_id === athleteId);
}
