// This file is generated by scripts/import-csv.ts. Do not edit directly.

import { EventStatus } from "./events";
import { athletes } from "./athletes";
import { entries } from "./entries";
import { personalBests } from "./personalBests";
import { resultRecords } from "./results";
import { universities } from "./universities";

export type RaceStart = {
  lane: number;
  athlete: string;
  athleteId: string;
  university: string;
  universityId: string;
  year: string;
  pb: string;
  entryStatus: "entered" | "listed" | "started" | "dns" | "unconfirmed";
  tag?: string;
  featured?: boolean;
};

export type RaceResultEntry = {
  rank: number | "-";
  athlete: string;
  athleteId: string;
  university: string;
  universityId: string;
  year: string;
  time: string;
  note?: "PB" | "SB" | "DNS" | "DNF" | "DQ";
};

export type RaceRecord = {
  race_id: string;
  slug: string;
  meet_id: string;
  race_name: string;
  start_time: string;
  status: "scheduled" | "startlist_published" | "result_published" | "result_waiting";
  distance: "1500m" | "5000m" | "10000m" | "ハーフ";
  result_summary_id?: string;
};

export type RaceDetail = {
  id: string;
  eventId: string;
  name: string;
  eventName: string;
  startTime: string;
  status: EventStatus;
  distance: string;
  summary: string;
  focus: string[];
  startList: RaceStart[];
  results: RaceResultEntry[];
  relatedRaces: { id: string; name: string; startTime: string; status: EventStatus }[];
  relatedUniversityIds: string[];
};

export const raceRecords: RaceRecord[] = [
  {
    "race_id": "kanto-intercollege-mens-5000m",
    "slug": "kanto-intercollege-mens-5000m",
    "meet_id": "kanto-intercollege",
    "race_name": "男子1部 5000m 決勝",
    "start_time": "開始時刻未定",
    "status": "result_published",
    "distance": "5000m",
    "result_summary_id": "kanto-intercollege-mens-5000m"
  },
  {
    "race_id": "japan-student-individual-mens-10000m",
    "slug": "japan-student-individual-mens-10000m",
    "meet_id": "japan-student-individual",
    "race_name": "男子 日本インカレ10000m 決勝",
    "start_time": "18:00",
    "status": "result_published",
    "distance": "10000m",
    "result_summary_id": "japan-student-individual-mens-10000m"
  },
  {
    "race_id": "japan-student-individual-mens-5000m",
    "slug": "japan-student-individual-mens-5000m",
    "meet_id": "japan-student-individual",
    "race_name": "男子 日本インカレ5000m 決勝",
    "start_time": "開始時刻未定",
    "status": "result_published",
    "distance": "5000m",
    "result_summary_id": "japan-student-individual-mens-5000m"
  },
  {
    "race_id": "kanto-intercollege-half-mens-division1",
    "slug": "kanto-intercollege-half-mens-division1",
    "meet_id": "kanto-intercollege-half",
    "race_name": "男子1部 ハーフマラソン 決勝",
    "start_time": "開始時刻未定",
    "status": "result_published",
    "distance": "ハーフ",
    "result_summary_id": "kanto-intercollege-half-mens-division1"
  },
  {
    "race_id": "kanto-intercollege-mens-division2-5000m",
    "slug": "kanto-intercollege-mens-division2-5000m",
    "meet_id": "kanto-intercollege",
    "race_name": "男子2部 5000m 決勝",
    "start_time": "9:55",
    "status": "result_published",
    "distance": "5000m",
    "result_summary_id": "kanto-intercollege-mens-division2-5000m"
  },
  {
    "race_id": "kanto-intercollege-half-mens-division2",
    "slug": "kanto-intercollege-half-mens-division2",
    "meet_id": "kanto-intercollege-half",
    "race_name": "男子2部 ハーフマラソン 決勝",
    "start_time": "開始時刻未定",
    "status": "result_published",
    "distance": "ハーフ",
    "result_summary_id": "kanto-intercollege-half-mens-division2"
  },
  {
    "race_id": "kanaguri-memorial-mens-gp-10000m",
    "slug": "kanaguri-memorial-mens-gp-10000m",
    "meet_id": "kanaguri-memorial",
    "race_name": "男子グランプリ 10000m 決勝",
    "start_time": "開始時刻未定",
    "status": "result_published",
    "distance": "10000m",
    "result_summary_id": "kanaguri-memorial-mens-gp-10000m"
  },
  {
    "race_id": "all-japan-kanto-qualifier-mens-10000m-overall",
    "slug": "all-japan-kanto-qualifier-mens-10000m-overall",
    "meet_id": "all-japan-kanto-qualifier",
    "race_name": "男子10000m タイムレース総合",
    "start_time": "開始時刻未定",
    "status": "result_published",
    "distance": "10000m",
    "result_summary_id": "all-japan-kanto-qualifier-mens-10000m-overall"
  },
  {
    "race_id": "kanto-intercollege-mens-10000m",
    "slug": "kanto-intercollege-mens-10000m",
    "meet_id": "kanto-intercollege",
    "race_name": "男子1部 10000m 決勝",
    "start_time": "開始時刻未定",
    "status": "result_published",
    "distance": "10000m",
    "result_summary_id": "kanto-intercollege-mens-10000m"
  },
  {
    "race_id": "kanto-intercollege-mens-division2-10000m",
    "slug": "kanto-intercollege-mens-division2-10000m",
    "meet_id": "kanto-intercollege",
    "race_name": "男子2部 10000m 決勝",
    "start_time": "18:50",
    "status": "result_published",
    "distance": "10000m",
    "result_summary_id": "kanto-intercollege-mens-division2-10000m"
  },
  {
    "race_id": "kanaguri-memorial-mens-gp-5000m",
    "slug": "kanaguri-memorial-mens-gp-5000m",
    "meet_id": "kanaguri-memorial",
    "race_name": "男子グランプリ 5000m タイムレース総合",
    "start_time": "開始時刻未定",
    "status": "result_published",
    "distance": "5000m",
    "result_summary_id": "kanaguri-memorial-mens-gp-5000m"
  },
  {
    "race_id": "golden-games-nobeoka-mens-5000m-overall",
    "slug": "golden-games-nobeoka-mens-5000m-overall",
    "meet_id": "golden-games-nobeoka",
    "race_name": "男子5000m タイムレース総合",
    "start_time": "開始時刻未定",
    "status": "result_published",
    "distance": "5000m",
    "result_summary_id": "golden-games-nobeoka-mens-5000m-overall"
  },
  {
    "race_id": "japan-championships-2026-mens-1500m-heats",
    "slug": "japan-championships-2026-mens-1500m-heats",
    "meet_id": "japan-championships-2026",
    "race_name": "日本選手権男子1500m 予選",
    "start_time": "14:38",
    "status": "startlist_published",
    "distance": "1500m"
  }
];

const meetNameById: Record<string, string> = {
  "kanto-intercollege": "関東インカレ",
  "japan-student-individual": "2026日本学生陸上競技個人選手権大会",
  "kanto-intercollege-half": "第105回関東学生陸上競技対校選手権大会 ハーフマラソン",
  "all-japan-kanto-qualifier": "秩父宮賜杯第58回全日本大学駅伝対校選手権大会 関東選考会",
  "golden-games-nobeoka": "第37回ゴールデンゲームズ in のべおか",
  "kanaguri-memorial": "第34回 金栗記念選抜陸上中長距離熊本大会",
  "japan-championships-2026": "第110回日本陸上競技選手権大会"
};

const statusMap: Record<RaceRecord["status"], EventStatus> = {
  scheduled: "scheduled",
  startlist_published: "startlist",
  result_published: "result",
  result_waiting: "waiting"
};

export const races: RaceDetail[] = raceRecords.map((race) => {
  const raceEntries = entries.filter((entry) => entry.race_id === race.race_id);
  const raceResults = resultRecords.filter((result) => result.race_id === race.race_id);
  const relatedRaces = raceRecords
    .filter((item) => item.meet_id === race.meet_id && item.race_id !== race.race_id)
    .map((item) => ({ id: item.race_id, name: item.race_name, startTime: item.start_time, status: statusMap[item.status] }));

  return {
    id: race.race_id,
    eventId: race.meet_id,
    name: race.race_name,
    eventName: meetNameById[race.meet_id] ?? race.meet_id,
    startTime: race.start_time,
    status: statusMap[race.status],
    distance: race.distance,
    summary: "掲載データ内の出場予定、結果、大学別の出場選手を確認できます。",
    focus: ["掲載PB", "掲載選手", "掲載結果"],
    startList: raceEntries.map((entry, index) => {
      const athlete = athletes.find((item) => item.id === entry.athlete_id);
      const university = universities.find((item) => item.id === entry.university_id);
      const pb = personalBests.find((record) => record.athlete_id === entry.athlete_id && record.distance === race.distance);

      return {
        lane: entry.bib_no ?? index + 1,
        athlete: athlete?.name ?? "未登録",
        athleteId: entry.athlete_id,
        university: university?.name ?? "大学未登録",
        universityId: entry.university_id,
        year: athlete?.year ?? "学年未登録",
        pb: pb ? `${pb.distance} ${pb.time}` : "PB未登録",
        entryStatus: entry.status
      };
    }),
    results: raceResults.map((result) => {
      const athlete = athletes.find((item) => item.id === result.athlete_id);
      const university = universities.find((item) => item.id === result.university_id);

      return {
        rank: result.rank === "DNS" ? "-" : Number.parseInt(result.rank, 10) || "-",
        athlete: athlete?.name ?? "未登録",
        athleteId: result.athlete_id,
        university: university?.name ?? "大学未登録",
        universityId: result.university_id,
        year: athlete?.year ?? "学年未登録",
        time: result.time,
        note: result.note
      };
    }),
    relatedRaces,
    relatedUniversityIds: Array.from(new Set(raceEntries.map((entry) => entry.university_id)))
  };
});

export function getRaceById(id: string) {
  return races.find((race) => race.id === id);
}

export function getRaceRecordById(id: string) {
  return raceRecords.find((race) => race.race_id === id);
}

export function getRacesByMeetId(meetId: string) {
  return raceRecords.filter((race) => race.meet_id === meetId);
}
