// This file is generated by scripts/import-csv.ts. Do not edit directly.

export type TeamResultType = "総合" | "往路" | "復路";

export type TeamResult = {
  team_result_id: string;
  meet_id: string;
  race_id: string;
  university_id: string;
  result_type: TeamResultType;
  rank: string;
  time: string;
  status: "finished" | "dns" | "dnf" | "dq";
  note?: string;
};

export const teamResults: TeamResult[] = [];

const resultTypeOrder: Record<TeamResultType, number> = { 総合: 0, 往路: 1, 復路: 2 };

export function getTeamResultsByRaceId(raceId: string) {
  return teamResults
    .filter((row) => row.race_id === raceId)
    .sort((a, b) => resultTypeOrder[a.result_type] - resultTypeOrder[b.result_type] || rankValue(a.rank) - rankValue(b.rank));
}

export function getTeamResultsByUniversityId(universityId: string) {
  return teamResults.filter((row) => row.university_id === universityId);
}

function rankValue(rank: string) {
  const parsed = Number.parseInt(rank, 10);
  return Number.isNaN(parsed) ? Number.POSITIVE_INFINITY : parsed;
}
