// This file is generated by scripts/import-csv.ts. Do not edit directly.

import type { Athlete } from "./athletes";

export type University = {
  id: string;
  slug: string;
  name: string;
  area: string;
  sashColor: string;
  accent: string;
  profile: string;
  style: string;
  coachNote: string;
  bestEkiden: string;
  athletes: string[];
  listing: {
    region: string;
    events: Array<"1500m" | "5000m" | "10000m" | "ハーフ">;
    nextAppearance: string;
    latestResult: {
      athlete: string;
      event: "1500m" | "5000m" | "10000m" | "ハーフ";
      time: string;
    };
    hasUpcoming: boolean;
    hasResult: boolean;
  };
};

export const universities: University[] = [
  {
    "id": "aoba",
    "slug": "aoba",
    "name": "早稲田",
    "area": "関東",
    "sashColor": "赤",
    "accent": "#b3263a",
    "profile": "男子長距離・駅伝の出場予定、最近の結果、種目別PB上位を確認できます。",
    "style": "5000m / 10000m / ハーフ",
    "coachNote": "出場予定と結果を掲載",
    "bestEkiden": "未登録",
    "athletes": [
      "saeki"
    ],
    "listing": {
      "region": "関東",
      "events": [
        "5000m",
        "10000m",
        "ハーフ"
      ],
      "nextAppearance": "関東学生10000m記録挑戦会",
      "latestResult": {
        "athlete": "佐伯 蒼",
        "event": "1500m",
        "time": "3:48.20"
      },
      "hasUpcoming": true,
      "hasResult": true
    }
  },
  {
    "id": "surugadai",
    "slug": "surugadai",
    "name": "青山学院",
    "area": "関東",
    "sashColor": "緑",
    "accent": "#158b63",
    "profile": "男子長距離・駅伝の出場予定、最近の結果、種目別PB上位を確認できます。",
    "style": "5000m / 10000m",
    "coachNote": "出場予定と結果を掲載",
    "bestEkiden": "未登録",
    "athletes": [
      "yoshioka"
    ],
    "listing": {
      "region": "関東",
      "events": [
        "5000m",
        "10000m"
      ],
      "nextAppearance": "関東学生10000m記録挑戦会",
      "latestResult": {
        "athlete": "未登録",
        "event": "5000m",
        "time": "未登録"
      },
      "hasUpcoming": true,
      "hasResult": true
    }
  },
  {
    "id": "josai",
    "slug": "josai",
    "name": "駒澤",
    "area": "関東",
    "sashColor": "紫",
    "accent": "#5b3c99",
    "profile": "男子長距離・駅伝の出場予定、最近の結果、種目別PB上位を確認できます。",
    "style": "10000m / ハーフ",
    "coachNote": "出場予定と結果を掲載",
    "bestEkiden": "未登録",
    "athletes": [
      "morino"
    ],
    "listing": {
      "region": "関東",
      "events": [
        "10000m",
        "ハーフ"
      ],
      "nextAppearance": "箱根駅伝予選会プレ記録会",
      "latestResult": {
        "athlete": "森野 健太",
        "event": "ハーフ",
        "time": "1:02:48"
      },
      "hasUpcoming": true,
      "hasResult": true
    }
  }
];

export type UniversityPbEvent = "5000m" | "10000m" | "ハーフ";

export type UniversityPbRanking = {
  event: UniversityPbEvent;
  entries: {
    rank: number;
    university: string;
    athlete: string;
    time: string;
  }[];
};

const pbEvents: UniversityPbEvent[] = ["5000m", "10000m", "ハーフ"];

export function buildUniversityPbRankings(universityList: University[], athleteList: Athlete[]): UniversityPbRanking[] {
  const universityById = new Map(universityList.map((university) => [university.id, university]));

  return pbEvents.map((event) => {
    const fastestByUniversity = new Map<string, { university: string; athlete: string; time: string; seconds: number }>();

    athleteList.forEach((athlete) => {
      const university = universityById.get(athlete.universityId);
      const pb = athlete.pb.find((record) => record.distance === event);

      if (!university || !pb) return;

      const seconds = toSeconds(pb.time);
      const current = fastestByUniversity.get(university.id);

      if (!current || seconds < current.seconds) {
        fastestByUniversity.set(university.id, { university: university.name, athlete: athlete.name, time: pb.time, seconds });
      }
    });

    const entries = Array.from(fastestByUniversity.values())
      .sort((a, b) => a.seconds - b.seconds)
      .slice(0, 3)
      .map((entry, index) => ({ rank: index + 1, university: entry.university, athlete: entry.athlete, time: entry.time }));

    return { event, entries };
  });
}

function toSeconds(time: string) {
  const parts = time.split(":").map(Number);

  if (parts.length === 3) {
    const [hours, minutes, seconds] = parts;
    return hours * 3600 + minutes * 60 + seconds;
  }

  const [minutes, seconds] = parts;
  return minutes * 60 + seconds;
}
